local H        = require("src/slicer/heap")
-- local fixtures = require("src/slicer/heap_fixtures")
describe("heap", function()
  it("has entries", function ()
    local heap = H.new()
    assert.has_error(function()
      local BAD_ADDRESS = 99
      heap.put(BAD_ADDRESS, "A", "B")
    end)
    assert.are_same(heap.here, H.NULL)
    local addr = heap.allot("foo")
    assert.are_same(heap.here, H.NULL + 1)
    assert.are_same(heap.entries:len(), 2)
    heap.put(addr, "A", "B")
    local cell = heap.entries[addr]
    assert.are_same(cell[H.KIND], "foo")
    assert.are_same(cell.A,    "B")
  end)
end)
